/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Store = IDL.Record({
  'latitude' : IDL.Float64,
  'ownerName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'storeName' : IDL.Text,
  'timestamp' : IDL.Int,
  'landmark' : IDL.Text,
});
export const AppUserRole = IDL.Variant({
  'admin' : IDL.Null,
  'distributor' : IDL.Null,
  'staff' : IDL.Null,
  'delivery' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'role' : AppUserRole,
  'email' : IDL.Text,
  'hashedPassword' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const DistributorDelivery = IDL.Record({
  'distributor' : IDL.Principal,
  'deliveryId' : IDL.Text,
  'estimatedDeliveryTime' : Time,
  'orderId' : IDL.Text,
  'driverContact' : IDL.Text,
  'notes' : IDL.Text,
  'truckNumber' : IDL.Text,
  'driverName' : IDL.Text,
});
export const GpsLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const QRCodeData = IDL.Record({
  'value' : IDL.Text,
  'scanned' : IDL.Bool,
  'scanTimestamp' : IDL.Opt(Time),
});
export const OrderRecord = IDL.Record({
  'status' : IDL.Text,
  'invoicePDF' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'emptyTruckImage' : IDL.Opt(ExternalBlob),
  'storeId' : IDL.Nat,
  'loadedTruckImage' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'rate' : IDL.Float64,
  'orderId' : IDL.Text,
  'gpsLocation' : IDL.Opt(GpsLocation),
  'notes' : IDL.Text,
  'barcodeScan' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'unloadedTruckImage' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'qrCode' : IDL.Opt(QRCodeData),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmptyTruckImage' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [], []),
  'addGpsLocation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'addStore' : IDL.Func([Store, IDL.Text], [], []),
  'addUser' : IDL.Func(
      [
        IDL.Record({
          'role' : AppUserRole,
          'email' : IDL.Text,
          'hashedPassword' : IDL.Text,
        }),
        IDL.Text,
      ],
      [User],
      [],
    ),
  'approveOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDistributorDelivery' : IDL.Func(
      [DistributorDelivery, IDL.Text],
      [],
      [],
    ),
  'createOrder' : IDL.Func([OrderRecord, IDL.Text], [], []),
  'deleteDistributorDelivery' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteStore' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'filterOrdersByStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(OrderRecord)],
      ['query'],
    ),
  'getAdminDashboardStats' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'activeDeliveries' : IDL.Nat,
          'pendingApproval' : IDL.Nat,
          'deliveredToday' : IDL.Nat,
          'confirmationsPending' : IDL.Nat,
          'totalOrdersToday' : IDL.Nat,
          'trucksInTransit' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllDistributorDeliveries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DistributorDelivery)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(OrderRecord)], ['query']),
  'getAllStores' : IDL.Func([IDL.Text], [IDL.Vec(Store)], ['query']),
  'getAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeliveryVerificationRecords' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'distributor' : IDL.Principal,
            'emptyTruckImage' : IDL.Opt(ExternalBlob),
            'loadedTruckImage' : IDL.Opt(IDL.Vec(IDL.Nat8)),
            'orderId' : IDL.Text,
            'storeRecord' : IDL.Opt(Store),
            'storeName' : IDL.Text,
            'timestamp' : IDL.Int,
            'orderContents' : IDL.Record({
              'rate' : IDL.Float64,
              'notes' : IDL.Text,
              'quantity' : IDL.Nat,
            }),
            'truckNumber' : IDL.Text,
            'driverName' : IDL.Text,
            'unloadedTruckImage' : IDL.Opt(IDL.Vec(IDL.Nat8)),
          })
        ),
      ],
      ['query'],
    ),
  'getDistributorDeliveriesByUser' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(DistributorDelivery)],
      ['query'],
    ),
  'getDistributorDelivery' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(DistributorDelivery)],
      ['query'],
    ),
  'getEmptyTruckImage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getLiveTrackingData' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'status' : IDL.Text,
            'orderId' : IDL.Text,
            'location' : IDL.Opt(GpsLocation),
          })
        ),
      ],
      ['query'],
    ),
  'getOrder' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(OrderRecord)],
      ['query'],
    ),
  'getOrderWithImages' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(OrderRecord)],
      ['query'],
    ),
  'getOrderWorkflowStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSystem' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Record({ 'token' : IDL.Text, 'role' : IDL.Text }))],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDistributorConfirmation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8), IDL.Text],
      [],
      [],
    ),
  'updateDistributorDelivery' : IDL.Func(
      [IDL.Text, DistributorDelivery, IDL.Text],
      [],
      [],
    ),
  'updateOrder' : IDL.Func([IDL.Text, OrderRecord, IDL.Text], [], []),
  'updateOrderStatusUsingQR' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateStore' : IDL.Func([IDL.Nat, Store, IDL.Text], [], []),
  'updateUser' : IDL.Func([IDL.Text, User, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Store = IDL.Record({
    'latitude' : IDL.Float64,
    'ownerName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'storeName' : IDL.Text,
    'timestamp' : IDL.Int,
    'landmark' : IDL.Text,
  });
  const AppUserRole = IDL.Variant({
    'admin' : IDL.Null,
    'distributor' : IDL.Null,
    'staff' : IDL.Null,
    'delivery' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'role' : AppUserRole,
    'email' : IDL.Text,
    'hashedPassword' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const DistributorDelivery = IDL.Record({
    'distributor' : IDL.Principal,
    'deliveryId' : IDL.Text,
    'estimatedDeliveryTime' : Time,
    'orderId' : IDL.Text,
    'driverContact' : IDL.Text,
    'notes' : IDL.Text,
    'truckNumber' : IDL.Text,
    'driverName' : IDL.Text,
  });
  const GpsLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const QRCodeData = IDL.Record({
    'value' : IDL.Text,
    'scanned' : IDL.Bool,
    'scanTimestamp' : IDL.Opt(Time),
  });
  const OrderRecord = IDL.Record({
    'status' : IDL.Text,
    'invoicePDF' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'emptyTruckImage' : IDL.Opt(ExternalBlob),
    'storeId' : IDL.Nat,
    'loadedTruckImage' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'rate' : IDL.Float64,
    'orderId' : IDL.Text,
    'gpsLocation' : IDL.Opt(GpsLocation),
    'notes' : IDL.Text,
    'barcodeScan' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'unloadedTruckImage' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'qrCode' : IDL.Opt(QRCodeData),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmptyTruckImage' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [], []),
    'addGpsLocation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'addStore' : IDL.Func([Store, IDL.Text], [], []),
    'addUser' : IDL.Func(
        [
          IDL.Record({
            'role' : AppUserRole,
            'email' : IDL.Text,
            'hashedPassword' : IDL.Text,
          }),
          IDL.Text,
        ],
        [User],
        [],
      ),
    'approveOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDistributorDelivery' : IDL.Func(
        [DistributorDelivery, IDL.Text],
        [],
        [],
      ),
    'createOrder' : IDL.Func([OrderRecord, IDL.Text], [], []),
    'deleteDistributorDelivery' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteStore' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'filterOrdersByStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(OrderRecord)],
        ['query'],
      ),
    'getAdminDashboardStats' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'activeDeliveries' : IDL.Nat,
            'pendingApproval' : IDL.Nat,
            'deliveredToday' : IDL.Nat,
            'confirmationsPending' : IDL.Nat,
            'totalOrdersToday' : IDL.Nat,
            'trucksInTransit' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllDistributorDeliveries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DistributorDelivery)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(OrderRecord)], ['query']),
    'getAllStores' : IDL.Func([IDL.Text], [IDL.Vec(Store)], ['query']),
    'getAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeliveryVerificationRecords' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'distributor' : IDL.Principal,
              'emptyTruckImage' : IDL.Opt(ExternalBlob),
              'loadedTruckImage' : IDL.Opt(IDL.Vec(IDL.Nat8)),
              'orderId' : IDL.Text,
              'storeRecord' : IDL.Opt(Store),
              'storeName' : IDL.Text,
              'timestamp' : IDL.Int,
              'orderContents' : IDL.Record({
                'rate' : IDL.Float64,
                'notes' : IDL.Text,
                'quantity' : IDL.Nat,
              }),
              'truckNumber' : IDL.Text,
              'driverName' : IDL.Text,
              'unloadedTruckImage' : IDL.Opt(IDL.Vec(IDL.Nat8)),
            })
          ),
        ],
        ['query'],
      ),
    'getDistributorDeliveriesByUser' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(DistributorDelivery)],
        ['query'],
      ),
    'getDistributorDelivery' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(DistributorDelivery)],
        ['query'],
      ),
    'getEmptyTruckImage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getLiveTrackingData' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'status' : IDL.Text,
              'orderId' : IDL.Text,
              'location' : IDL.Opt(GpsLocation),
            })
          ),
        ],
        ['query'],
      ),
    'getOrder' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(OrderRecord)],
        ['query'],
      ),
    'getOrderWithImages' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(OrderRecord)],
        ['query'],
      ),
    'getOrderWorkflowStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSystem' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Record({ 'token' : IDL.Text, 'role' : IDL.Text }))],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDistributorConfirmation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8), IDL.Text],
        [],
        [],
      ),
    'updateDistributorDelivery' : IDL.Func(
        [IDL.Text, DistributorDelivery, IDL.Text],
        [],
        [],
      ),
    'updateOrder' : IDL.Func([IDL.Text, OrderRecord, IDL.Text], [], []),
    'updateOrderStatusUsingQR' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateStore' : IDL.Func([IDL.Nat, Store, IDL.Text], [], []),
    'updateUser' : IDL.Func([IDL.Text, User, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };