/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Store = IDL.Record({
  'latitude' : IDL.Float64,
  'ownerName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'storeName' : IDL.Text,
  'timestamp' : IDL.Int,
  'landmark' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const User = IDL.Record({
  'role' : UserRole,
  'email' : IDL.Text,
  'hashedPassword' : IDL.Text,
});
export const Time = IDL.Int;
export const DistributorDelivery = IDL.Record({
  'distributor' : IDL.Principal,
  'deliveryId' : IDL.Text,
  'estimatedDeliveryTime' : Time,
  'orderId' : IDL.Text,
  'driverContact' : IDL.Text,
  'notes' : IDL.Text,
  'truckNumber' : IDL.Text,
  'driverName' : IDL.Text,
});
export const OrderRecord = IDL.Record({
  'status' : IDL.Text,
  'storeId' : IDL.Nat,
  'rate' : IDL.Float64,
  'orderId' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStore' : IDL.Func([Store], [], []),
  'addUser' : IDL.Func([User], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDistributorDelivery' : IDL.Func([DistributorDelivery], [], []),
  'createOrder' : IDL.Func([OrderRecord], [], []),
  'deleteDistributorDelivery' : IDL.Func([IDL.Text], [], []),
  'deleteStore' : IDL.Func([IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'getAllDistributorDeliveries' : IDL.Func(
      [],
      [IDL.Vec(DistributorDelivery)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDistributorDeliveriesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DistributorDelivery)],
      ['query'],
    ),
  'getDistributorDelivery' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DistributorDelivery)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(OrderRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSystem' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDistributorDelivery' : IDL.Func(
      [IDL.Text, DistributorDelivery],
      [],
      [],
    ),
  'updateOrder' : IDL.Func([IDL.Text, OrderRecord], [], []),
  'updateStore' : IDL.Func([IDL.Nat, Store], [], []),
  'updateUser' : IDL.Func([IDL.Text, User], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Store = IDL.Record({
    'latitude' : IDL.Float64,
    'ownerName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'storeName' : IDL.Text,
    'timestamp' : IDL.Int,
    'landmark' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const User = IDL.Record({
    'role' : UserRole,
    'email' : IDL.Text,
    'hashedPassword' : IDL.Text,
  });
  const Time = IDL.Int;
  const DistributorDelivery = IDL.Record({
    'distributor' : IDL.Principal,
    'deliveryId' : IDL.Text,
    'estimatedDeliveryTime' : Time,
    'orderId' : IDL.Text,
    'driverContact' : IDL.Text,
    'notes' : IDL.Text,
    'truckNumber' : IDL.Text,
    'driverName' : IDL.Text,
  });
  const OrderRecord = IDL.Record({
    'status' : IDL.Text,
    'storeId' : IDL.Nat,
    'rate' : IDL.Float64,
    'orderId' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStore' : IDL.Func([Store], [], []),
    'addUser' : IDL.Func([User], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDistributorDelivery' : IDL.Func([DistributorDelivery], [], []),
    'createOrder' : IDL.Func([OrderRecord], [], []),
    'deleteDistributorDelivery' : IDL.Func([IDL.Text], [], []),
    'deleteStore' : IDL.Func([IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'getAllDistributorDeliveries' : IDL.Func(
        [],
        [IDL.Vec(DistributorDelivery)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDistributorDeliveriesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DistributorDelivery)],
        ['query'],
      ),
    'getDistributorDelivery' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DistributorDelivery)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(OrderRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSystem' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDistributorDelivery' : IDL.Func(
        [IDL.Text, DistributorDelivery],
        [],
        [],
      ),
    'updateOrder' : IDL.Func([IDL.Text, OrderRecord], [], []),
    'updateStore' : IDL.Func([IDL.Nat, Store], [], []),
    'updateUser' : IDL.Func([IDL.Text, User], [], []),
  });
};

export const init = ({ IDL }) => { return []; };