/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DistributorDelivery {
  'distributor' : Principal,
  'deliveryId' : string,
  'estimatedDeliveryTime' : Time,
  'orderId' : string,
  'driverContact' : string,
  'notes' : string,
  'truckNumber' : string,
  'driverName' : string,
}
export interface OrderRecord {
  'status' : string,
  'storeId' : bigint,
  'rate' : number,
  'orderId' : string,
  'notes' : string,
  'timestamp' : bigint,
  'quantity' : bigint,
}
export interface Store {
  'latitude' : number,
  'ownerName' : string,
  'mobileNumber' : string,
  'longitude' : number,
  'address' : string,
  'storeName' : string,
  'timestamp' : bigint,
  'landmark' : string,
}
export type Time = bigint;
export interface User {
  'role' : UserRole,
  'email' : string,
  'hashedPassword' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStore' : ActorMethod<[Store], undefined>,
  'addUser' : ActorMethod<[User], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDistributorDelivery' : ActorMethod<[DistributorDelivery], undefined>,
  'createOrder' : ActorMethod<[OrderRecord], undefined>,
  'deleteDistributorDelivery' : ActorMethod<[string], undefined>,
  'deleteStore' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[string], undefined>,
  'getAllDistributorDeliveries' : ActorMethod<[], Array<DistributorDelivery>>,
  'getAllOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getAllStores' : ActorMethod<[], Array<Store>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDistributorDeliveriesByUser' : ActorMethod<
    [Principal],
    Array<DistributorDelivery>
  >,
  'getDistributorDelivery' : ActorMethod<[string], [] | [DistributorDelivery]>,
  'getOrder' : ActorMethod<[string], [] | [OrderRecord]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSystem' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDistributorDelivery' : ActorMethod<
    [string, DistributorDelivery],
    undefined
  >,
  'updateOrder' : ActorMethod<[string, OrderRecord], undefined>,
  'updateStore' : ActorMethod<[bigint, Store], undefined>,
  'updateUser' : ActorMethod<[string, User], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];