/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'admin' : null } |
  { 'distributor' : null } |
  { 'staff' : null } |
  { 'delivery' : null };
export interface CreateOrderInput {
  'invoicePDF' : [] | [Uint8Array],
  'storeId' : bigint,
  'rate' : number,
  'orderId' : string,
  'notes' : string,
  'timestamp' : bigint,
  'quantity' : bigint,
}
export interface DistributorDelivery {
  'distributor' : Principal,
  'deliveryId' : string,
  'estimatedDeliveryTime' : Time,
  'orderId' : string,
  'driverContact' : string,
  'notes' : string,
  'truckNumber' : string,
  'driverName' : string,
}
export type ExternalBlob = Uint8Array;
export interface GpsLocation {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : bigint,
}
export interface OrderRecord {
  'status' : string,
  'invoicePDF' : [] | [Uint8Array],
  'emptyTruckImage' : [] | [ExternalBlob],
  'storeId' : bigint,
  'loadedTruckImage' : [] | [Uint8Array],
  'rate' : number,
  'assignedDeliveryUser' : [] | [Principal],
  'orderId' : string,
  'gpsLocation' : [] | [GpsLocation],
  'notes' : string,
  'barcodeScan' : [] | [string],
  'timestamp' : bigint,
  'quantity' : bigint,
  'unloadedTruckImage' : [] | [Uint8Array],
  'qrCode' : [] | [QRCodeData],
}
export interface QRCodeData {
  'value' : string,
  'scanned' : boolean,
  'scanTimestamp' : [] | [Time],
}
export interface Store {
  'latitude' : number,
  'ownerName' : string,
  'mobileNumber' : string,
  'longitude' : number,
  'address' : string,
  'storeName' : string,
  'timestamp' : bigint,
  'landmark' : string,
}
export type Time = bigint;
export interface User {
  'id' : string,
  'role' : AppUserRole,
  'email' : string,
  'hashedPassword' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEmptyTruckImage' : ActorMethod<[string, ExternalBlob, string], undefined>,
  'addGpsLocation' : ActorMethod<[string, number, number, string], undefined>,
  'addStore' : ActorMethod<[Store, string], undefined>,
  'addUser' : ActorMethod<
    [
      { 'role' : AppUserRole, 'email' : string, 'hashedPassword' : string },
      string,
    ],
    User
  >,
  'approveOrder' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDelivery' : ActorMethod<[string, Principal, string], undefined>,
  'createDistributorDelivery' : ActorMethod<
    [DistributorDelivery, string],
    undefined
  >,
  'createOrder' : ActorMethod<[CreateOrderInput, string], undefined>,
  'deleteDistributorDelivery' : ActorMethod<[string, string], undefined>,
  'deleteStore' : ActorMethod<[bigint, string], undefined>,
  'deleteUser' : ActorMethod<[string, string], undefined>,
  'filterOrdersByStatus' : ActorMethod<[string, string], Array<OrderRecord>>,
  'getAdminDashboardStats' : ActorMethod<
    [string],
    {
      'activeDeliveries' : bigint,
      'pendingApproval' : bigint,
      'deliveredToday' : bigint,
      'confirmationsPending' : bigint,
      'totalOrdersToday' : bigint,
      'trucksInTransit' : bigint,
    }
  >,
  'getAllDistributorDeliveries' : ActorMethod<
    [string],
    Array<DistributorDelivery>
  >,
  'getAllOrders' : ActorMethod<[string], Array<OrderRecord>>,
  'getAllStores' : ActorMethod<[string], Array<Store>>,
  'getAllUsers' : ActorMethod<[string], Array<User>>,
  'getAssignedOrdersForDeliveryUser' : ActorMethod<
    [Principal, string],
    Array<OrderRecord>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeliveryVerificationRecords' : ActorMethod<
    [string],
    Array<
      {
        'distributor' : Principal,
        'emptyTruckImage' : [] | [ExternalBlob],
        'loadedTruckImage' : [] | [Uint8Array],
        'orderId' : string,
        'storeRecord' : [] | [Store],
        'storeName' : string,
        'timestamp' : bigint,
        'orderContents' : {
          'rate' : number,
          'notes' : string,
          'quantity' : bigint,
        },
        'truckNumber' : string,
        'driverName' : string,
        'unloadedTruckImage' : [] | [Uint8Array],
      }
    >
  >,
  'getDistributorDeliveriesByUser' : ActorMethod<
    [Principal, string],
    Array<DistributorDelivery>
  >,
  'getDistributorDelivery' : ActorMethod<
    [string, string],
    [] | [DistributorDelivery]
  >,
  'getEmptyTruckImage' : ActorMethod<[string, string], [] | [ExternalBlob]>,
  'getLiveTrackingData' : ActorMethod<
    [string],
    Array<
      { 'status' : string, 'orderId' : string, 'location' : [] | [GpsLocation] }
    >
  >,
  'getOrder' : ActorMethod<[string, string], [] | [OrderRecord]>,
  'getOrderWithImages' : ActorMethod<[string, string], [] | [OrderRecord]>,
  'getOrderWorkflowStatus' : ActorMethod<[string, string], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSystem' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [string, string],
    [] | [{ 'token' : string, 'role' : string }]
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDistributorConfirmation' : ActorMethod<
    [string, string, Uint8Array, Uint8Array, string],
    undefined
  >,
  'updateDistributorDelivery' : ActorMethod<
    [string, DistributorDelivery, string],
    undefined
  >,
  'updateOrder' : ActorMethod<[string, OrderRecord, string], undefined>,
  'updateOrderStatusByDeliveryUser' : ActorMethod<
    [string, string, string],
    undefined
  >,
  'updateOrderStatusUsingQR' : ActorMethod<[string, string, string], undefined>,
  'updateStore' : ActorMethod<[bigint, Store, string], undefined>,
  'updateUser' : ActorMethod<[string, User, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];